// Auto-generated command template
// Generated by sync-commands.js
// DO NOT EDIT MANUALLY

export interface Command {
  name: string;
  description: string;
  usage: string;
  category: string;
  exampleOutput: string;
  permission?: string;
}

export const COMMANDS: Command[] = [
  {
    "name": "8ball",
    "description": "\udfb1 Ask the magic 8-ball a question and receive a mystical fortune.",
    "usage": "|8ball",
    "category": "fun",
    "exampleOutput": "✓ 8ball  executed successfully."
  },
  {
    "name": "analytics setup",
    "description": "Deploy statistics channel grids (auto-refreshes every 1 min)",
    "usage": "|analytics setup",
    "category": "analytics",
    "exampleOutput": "📊 Analytics tracking deployed.",
    "permission": "Manage Server"
  },
  {
    "name": "analytics edit",
    "description": "✏️ Modify your existing statistics channel layout settings",
    "usage": "|analytics edit",
    "category": "analytics",
    "exampleOutput": "📊 Analytics tracking deployed.",
    "permission": "Manage Server"
  },
  {
    "name": "analytics delete",
    "description": "\uddd1️ Wipe current statistic channels and clear database traces",
    "usage": "|analytics delete",
    "category": "analytics",
    "exampleOutput": "📊 Analytics tracking deployed.",
    "permission": "Manage Server"
  },
  {
    "name": "analytics update",
    "description": "\udd04 Force an instant refresh (counters already auto-refresh every 1 min)",
    "usage": "|analytics update",
    "category": "analytics",
    "exampleOutput": "📊 Analytics tracking deployed.",
    "permission": "Manage Server"
  },
  {
    "name": "autodelete",
    "description": "The auto-delete profile for ${channel} is now active.",
    "usage": "|autodelete",
    "category": "utility",
    "exampleOutput": "✓ autodelete  executed successfully.",
    "permission": "Administrator"
  },
  {
    "name": "automessage",
    "description": "Manage recurring scheduled message pings",
    "usage": "|automessage",
    "category": "utility",
    "exampleOutput": "✓ automessage  executed successfully.",
    "permission": "Administrator"
  },
  {
    "name": "automodrule setup",
    "description": "Launch the interactive configuration setup wizard node",
    "usage": "|automodrule setup",
    "category": "automod",
    "exampleOutput": "✓ automodrule setup executed successfully."
  },
  {
    "name": "automodrule edit",
    "description": "✏️ Modify your existing background filter parameter fields",
    "usage": "|automodrule edit",
    "category": "automod",
    "exampleOutput": "✓ automodrule edit executed successfully."
  },
  {
    "name": "automodrule delete",
    "description": "\uddd1️ Wipe current filter metrics cleanly out of memory rows",
    "usage": "|automodrule delete",
    "category": "automod",
    "exampleOutput": "✓ automodrule delete executed successfully."
  },
  {
    "name": "autoresponder",
    "description": "Configure each part below. Your changes preview live. Click **Save** when ready.",
    "usage": "|autoresponder",
    "category": "automod",
    "exampleOutput": "✓ autoresponder  executed successfully.",
    "permission": "ManageGuild"
  },
  {
    "name": "autorole all",
    "description": "Apply role to everyone",
    "usage": "|autorole all",
    "category": "roles",
    "exampleOutput": "✓ Autorole configured successfully.",
    "permission": "Manage Roles"
  },
  {
    "name": "autorole humans",
    "description": "Apply role to humans only",
    "usage": "|autorole humans",
    "category": "roles",
    "exampleOutput": "✓ Autorole configured successfully.",
    "permission": "Manage Roles"
  },
  {
    "name": "autorole bots",
    "description": "Apply role to bots only",
    "usage": "|autorole bots",
    "category": "roles",
    "exampleOutput": "✓ Autorole configured successfully.",
    "permission": "Manage Roles"
  },
  {
    "name": "autorole ongoing",
    "description": "Inspect current active configurations",
    "usage": "|autorole ongoing",
    "category": "roles",
    "exampleOutput": "✓ Autorole configured successfully.",
    "permission": "Manage Roles"
  },
  {
    "name": "autorole delete",
    "description": "Purge all ongoing configs for everyone, bots, and humans",
    "usage": "|autorole delete",
    "category": "roles",
    "exampleOutput": "✓ Autorole configured successfully.",
    "permission": "Manage Roles"
  },
  {
    "name": "ban",
    "description": "Ban a user from the server",
    "usage": "|ban",
    "category": "moderation",
    "exampleOutput": "✓ Banned member @user (Reason: Malicious activity)",
    "permission": "BanMembers"
  },
  {
    "name": "birthdays",
    "description": "Birthday management",
    "usage": "|birthdays",
    "category": "social",
    "exampleOutput": "✓ birthdays  executed successfully.",
    "permission": "ManageGuild"
  },
  {
    "name": "capabilities",
    "description": "A full, detailed tour of everything the bot can do.",
    "usage": "|capabilities",
    "category": "utility",
    "exampleOutput": "✓ capabilities  executed successfully."
  },
  {
    "name": "capital-quiz",
    "description": "Tests your geographic knowledge of world capitals.",
    "usage": "|capital-quiz",
    "category": "fun",
    "exampleOutput": "✓ capital-quiz  executed successfully."
  },
  {
    "name": "cat",
    "description": "Spits out a fully animated cat GIF and a random feline fact.",
    "usage": "|cat",
    "category": "fun",
    "exampleOutput": "✓ cat  executed successfully."
  },
  {
    "name": "channels",
    "description": "Create, edit, customize, and delete channels and categories.",
    "usage": "|channels",
    "category": "utility",
    "exampleOutput": "✓ channels  executed successfully.",
    "permission": "ManageChannels"
  },
  {
    "name": "coinflip",
    "description": "Flip an animated coin and see what it lands on.",
    "usage": "|coinflip",
    "category": "fun",
    "exampleOutput": "✓ coinflip  executed successfully."
  },
  {
    "name": "cute",
    "description": "Configure cute text layouts for server setup templates",
    "usage": "|cute",
    "category": "setup",
    "exampleOutput": "✨ Cute Mode Configured! Layouts will now use Small Caps (sᴍᴀʟʟ ᴄᴀᴘs)!",
    "permission": "ManageGuild"
  },
  {
    "name": "dadjoke",
    "description": "Get a classic, groans-guaranteed dad joke.",
    "usage": "|dadjoke",
    "category": "fun",
    "exampleOutput": "✓ dadjoke  executed successfully."
  },
  {
    "name": "dice-duel",
    "description": "Challenge another user to an instant dice rolling duel.",
    "usage": "|dice-duel",
    "category": "fun",
    "exampleOutput": "✓ dice-duel  executed successfully."
  },
  {
    "name": "dog",
    "description": "Spits out a cute puppy picture and a random canine fact.",
    "usage": "|dog",
    "category": "fun",
    "exampleOutput": "✓ dog  executed successfully."
  },
  {
    "name": "embed create",
    "description": "Open a modal to build a new embed",
    "usage": "|embed create",
    "category": "utility",
    "exampleOutput": "✓ embed create executed successfully."
  },
  {
    "name": "embed edit",
    "description": "Load an existing bot embed into your session for editing",
    "usage": "|embed edit",
    "category": "utility",
    "exampleOutput": "✓ embed edit executed successfully."
  },
  {
    "name": "embed send",
    "description": "Send your in-progress embed to a channel",
    "usage": "|embed send",
    "category": "utility",
    "exampleOutput": "✓ embed send executed successfully."
  },
  {
    "name": "embed field add",
    "description": "Open a modal to add a field to your embed",
    "usage": "|embed field add",
    "category": "utility",
    "exampleOutput": "✓ embed add executed successfully."
  },
  {
    "name": "embed field remove",
    "description": "Remove a field from your embed by index",
    "usage": "|embed field remove",
    "category": "utility",
    "exampleOutput": "✓ embed remove executed successfully."
  },
  {
    "name": "embed field image",
    "description": "Set the large image URL on your embed",
    "usage": "|embed field image",
    "category": "utility",
    "exampleOutput": "✓ embed image executed successfully."
  },
  {
    "name": "embed thumbnail",
    "description": "Set the thumbnail URL on your embed",
    "usage": "|embed thumbnail",
    "category": "utility",
    "exampleOutput": "✓ embed thumbnail executed successfully."
  },
  {
    "name": "embed color",
    "description": "Set the embed color",
    "usage": "|embed color",
    "category": "utility",
    "exampleOutput": "✓ embed color executed successfully."
  },
  {
    "name": "embed footer",
    "description": "Set the embed footer",
    "usage": "|embed footer",
    "category": "utility",
    "exampleOutput": "✓ embed footer executed successfully."
  },
  {
    "name": "embed author",
    "description": "Set the embed author",
    "usage": "|embed author",
    "category": "utility",
    "exampleOutput": "✓ embed author executed successfully."
  },
  {
    "name": "embed preview",
    "description": "Preview your current in-progress embed",
    "usage": "|embed preview",
    "category": "utility",
    "exampleOutput": "✓ embed preview executed successfully."
  },
  {
    "name": "embed clear",
    "description": "Clear your in-progress embed session",
    "usage": "|embed clear",
    "category": "utility",
    "exampleOutput": "✓ embed clear executed successfully."
  },
  {
    "name": "embed template save",
    "description": "Save current embed as a named template",
    "usage": "|embed template save",
    "category": "utility",
    "exampleOutput": "✓ embed save executed successfully."
  },
  {
    "name": "embed template load",
    "description": "Load a saved template into your session",
    "usage": "|embed template load",
    "category": "utility",
    "exampleOutput": "✓ embed load executed successfully."
  },
  {
    "name": "embed list",
    "description": "List all saved templates for this server",
    "usage": "|embed list",
    "category": "utility",
    "exampleOutput": "✓ embed list executed successfully."
  },
  {
    "name": "embed delete",
    "description": "Delete a saved template",
    "usage": "|embed delete",
    "category": "utility",
    "exampleOutput": "✓ embed delete executed successfully."
  },
  {
    "name": "flavor",
    "description": "Discover your current ice cream flavor personality.",
    "usage": "|flavor",
    "category": "utility",
    "exampleOutput": "✓ flavor  executed successfully."
  },
  {
    "name": "fortune",
    "description": "Reveals a prediction about your future.",
    "usage": "|fortune",
    "category": "fun",
    "exampleOutput": "✓ fortune  executed successfully."
  },
  {
    "name": "fun-menu",
    "description": "Explore what the Fun Module offers in a clean single-column directory.",
    "usage": "|fun-menu",
    "category": "fun",
    "exampleOutput": "✓ fun-menu  executed successfully."
  },
  {
    "name": "fun-module",
    "description": "Enable or disable the fun commands module.",
    "usage": "|fun-module",
    "category": "setup",
    "exampleOutput": "✓ fun-module  executed successfully.",
    "permission": "ManageGuild"
  },
  {
    "name": "giveaway",
    "description": "Establish and manage customizable item drops",
    "usage": "|giveaway",
    "category": "social",
    "exampleOutput": "✓ giveaway  executed successfully.",
    "permission": "Administrator"
  },
  {
    "name": "guilds",
    "description": "Owner only: list all guilds the bot is in",
    "usage": "|guilds",
    "category": "utility",
    "exampleOutput": "✓ guilds  executed successfully.",
    "permission": "CreateInstantInvite"
  },
  {
    "name": "help",
    "description": "View the full list of available bot commands by category.",
    "usage": "|help",
    "category": "utility",
    "exampleOutput": "✓ help  executed successfully."
  },
  {
    "name": "hug",
    "description": "Give a member a warm, fuzzy virtual hug.",
    "usage": "|hug",
    "category": "fun",
    "exampleOutput": "✓ hug  executed successfully."
  },
  {
    "name": "invites",
    "description": "Advanced invite tracking system",
    "usage": "|invites",
    "category": "utility",
    "exampleOutput": "✓ invites  executed successfully.",
    "permission": "ManageGuild"
  },
  {
    "name": "joke",
    "description": "Get a hilariously relatable, funny everyday joke.",
    "usage": "|joke",
    "category": "fun",
    "exampleOutput": "✓ joke  executed successfully."
  },
  {
    "name": "kick",
    "description": "Kick a user from the server",
    "usage": "|kick",
    "category": "moderation",
    "exampleOutput": "✓ Kicked member @user",
    "permission": "KickMembers"
  },
  {
    "name": "level leaderboard",
    "description": "Show the top 10 users by XP",
    "usage": "|level leaderboard",
    "category": "leveling",
    "exampleOutput": "📈 Leveling system updated."
  },
  {
    "name": "level settings",
    "description": "Configure leveling settings",
    "usage": "|level settings",
    "category": "leveling",
    "exampleOutput": "📈 Leveling system updated."
  },
  {
    "name": "level multiplier",
    "description": "Set a server-wide XP multiplier (e.g., 2 for Double XP)",
    "usage": "|level multiplier",
    "category": "leveling",
    "exampleOutput": "📈 Leveling system updated."
  },
  {
    "name": "level xp add",
    "description": "Add XP to a user",
    "usage": "|level xp add",
    "category": "leveling",
    "exampleOutput": "📈 Leveling system updated."
  },
  {
    "name": "level xp remove",
    "description": "Remove XP from a user",
    "usage": "|level xp remove",
    "category": "leveling",
    "exampleOutput": "📈 Leveling system updated."
  },
  {
    "name": "lockdown",
    "description": "Freeze or thaw text channels during emergencies",
    "usage": "|lockdown",
    "category": "moderation",
    "exampleOutput": "✓ lockdown  executed successfully.",
    "permission": "Administrator"
  },
  {
    "name": "meme",
    "description": "Spits out a random funny, relatable lifestyle meme.",
    "usage": "|meme",
    "category": "fun",
    "exampleOutput": "✓ meme  executed successfully."
  },
  {
    "name": "mod-logs-toggle",
    "description": "Log all moderator actions into one channel.",
    "usage": "|mod-logs-toggle",
    "category": "utility",
    "exampleOutput": "✓ mod-logs-toggle  executed successfully.",
    "permission": "ManageGuild"
  },
  {
    "name": "mute",
    "description": "Mute a user for a custom duration (1m to 28d)",
    "usage": "|mute",
    "category": "moderation",
    "exampleOutput": "✓ Timed out @user for 10m",
    "permission": "ModerateMembers"
  },
  {
    "name": "mydata",
    "description": "No description",
    "usage": "|mydata",
    "category": "utility",
    "exampleOutput": "✓ mydata  executed successfully."
  },
  {
    "name": "poll",
    "description": "Create and manage polls",
    "usage": "|poll",
    "category": "social",
    "exampleOutput": "✓ poll  executed successfully.",
    "permission": "Administrator"
  },
  {
    "name": "predict-love",
    "description": "Calculate the ultimate romantic compatibility percentage.",
    "usage": "|predict-love",
    "category": "fun",
    "exampleOutput": "✓ predict-love  executed successfully."
  },
  {
    "name": "premium",
    "description": "Premium includes everything in the Free tier, plus the additions below.",
    "usage": "|premium",
    "category": "utility",
    "exampleOutput": "✓ premium  executed successfully.",
    "permission": "SendMessages"
  },
  {
    "name": "purge",
    "description": "Bulk delete messages using advanced filtering",
    "usage": "|purge",
    "category": "moderation",
    "exampleOutput": "✓ purge  executed successfully.",
    "permission": "Administrator"
  },
  {
    "name": "purpose",
    "description": "Learn about the bot and see its profile picture",
    "usage": "|purpose",
    "category": "utility",
    "exampleOutput": "✓ purpose  executed successfully."
  },
  {
    "name": "rate",
    "description": "Have the bot rate anything out of 10.",
    "usage": "|rate",
    "category": "fun",
    "exampleOutput": "✓ rate  executed successfully."
  },
  {
    "name": "reactionroles create",
    "description": "Build and deploy a custom role assignment panel",
    "usage": "|reactionroles create",
    "category": "roles",
    "exampleOutput": "✅ Role panel deployed successfully.",
    "permission": "Manage Roles"
  },
  {
    "name": "reactionroles edit",
    "description": "✏️ Update the title or description text fields of an existing deployed panel",
    "usage": "|reactionroles edit",
    "category": "roles",
    "exampleOutput": "✅ Role panel deployed successfully.",
    "permission": "Manage Roles"
  },
  {
    "name": "reactionroles add-role",
    "description": "➕ Add a new assignment choice node directly into an existing active panel",
    "usage": "|reactionroles add-role",
    "category": "roles",
    "exampleOutput": "✅ Role panel deployed successfully.",
    "permission": "Manage Roles"
  },
  {
    "name": "reactionroles remove-role",
    "description": "➖ Remove a specific role assignment node out of an active panel framework",
    "usage": "|reactionroles remove-role",
    "category": "roles",
    "exampleOutput": "✅ Role panel deployed successfully.",
    "permission": "Manage Roles"
  },
  {
    "name": "reactionroles delete-panel",
    "description": "\uddd1️ Wipe a role panel entirely out of active channel registries and database nodes",
    "usage": "|reactionroles delete-panel",
    "category": "roles",
    "exampleOutput": "✅ Role panel deployed successfully.",
    "permission": "Manage Roles"
  },
  {
    "name": "reactionroles test",
    "description": "🧪 Diagnostic Simulator: Test component menus safely in a private sandbox view",
    "usage": "|reactionroles test",
    "category": "roles",
    "exampleOutput": "✅ Role panel deployed successfully.",
    "permission": "Manage Roles"
  },
  {
    "name": "roast",
    "description": "Deliver a savage, good-natured roast to a user.",
    "usage": "|roast",
    "category": "fun",
    "exampleOutput": "✓ roast  executed successfully."
  },
  {
    "name": "role",
    "description": "Role management system",
    "usage": "|role",
    "category": "roles",
    "exampleOutput": "✓ Role management command executed successfully.",
    "permission": "ManageRoles"
  },
  {
    "name": "roll",
    "description": "Roll a random number or a multi-sided die.",
    "usage": "|roll",
    "category": "fun",
    "exampleOutput": "✓ roll  executed successfully."
  },
  {
    "name": "rules",
    "description": "Generate and customize server rules.",
    "usage": "|rules",
    "category": "utility",
    "exampleOutput": "✓ rules  executed successfully.",
    "permission": "Administrator"
  },
  {
    "name": "selfvoice",
    "description": "\udf99️ Create self-managed temporary voice channels that clean themselves up.",
    "usage": "|selfvoice",
    "category": "voice",
    "exampleOutput": "🔊 Voice room created successfully.",
    "permission": "Administrator"
  },
  {
    "name": "setup-audit",
    "description": "Configure, enable, or disable the server audit log channel.",
    "usage": "|setup-audit",
    "category": "setup",
    "exampleOutput": "✓ setup-audit  executed successfully.",
    "permission": "Administrator"
  },
  {
    "name": "setup",
    "description": "️ Provision specialized, high-density server configurations from blueprint templates.",
    "usage": "|setup",
    "category": "setup",
    "exampleOutput": "✓ Setup complete! Deployed: 📁 Welcome, 📁 Chats, 7 channels, and Admin/Mod/Member roles.",
    "permission": "ManageGuild"
  },
  {
    "name": "slap",
    "description": "Slap another user with a hilarious item.",
    "usage": "|slap",
    "category": "fun",
    "exampleOutput": "✓ slap  executed successfully."
  },
  {
    "name": "slowmode",
    "description": "Manage channel slowmode intervals",
    "usage": "|slowmode",
    "category": "moderation",
    "exampleOutput": "✓ slowmode  executed successfully.",
    "permission": "ManageMessages"
  },
  {
    "name": "spacefact",
    "description": "Get a mind-blowing cosmic space fact.",
    "usage": "|spacefact",
    "category": "fun",
    "exampleOutput": "✓ spacefact  executed successfully."
  },
  {
    "name": "starboard setup",
    "description": "Launch the setup wizard (or pass a channel to skip it)",
    "usage": "|starboard setup",
    "category": "utility",
    "exampleOutput": "✓ starboard setup executed successfully."
  },
  {
    "name": "starboard config",
    "description": "Configure a starboard setting",
    "usage": "|starboard config",
    "category": "utility",
    "exampleOutput": "✓ starboard config executed successfully."
  },
  {
    "name": "starboard ignore",
    "description": "Add a channel to the ignore list",
    "usage": "|starboard ignore",
    "category": "utility",
    "exampleOutput": "✓ starboard ignore executed successfully."
  },
  {
    "name": "starboard unignore",
    "description": "Remove a channel from the ignore list",
    "usage": "|starboard unignore",
    "category": "utility",
    "exampleOutput": "✓ starboard unignore executed successfully."
  },
  {
    "name": "starboard toggle",
    "description": "Enable or disable the starboard module",
    "usage": "|starboard toggle",
    "category": "utility",
    "exampleOutput": "✓ starboard toggle executed successfully."
  },
  {
    "name": "starboard force",
    "description": "Force-star a message by its ID",
    "usage": "|starboard force",
    "category": "utility",
    "exampleOutput": "✓ starboard force executed successfully."
  },
  {
    "name": "starboard stats",
    "description": "View starboard statistics for this server",
    "usage": "|starboard stats",
    "category": "utility",
    "exampleOutput": "✓ starboard stats executed successfully."
  },
  {
    "name": "stickies",
    "description": "Deploy and manage a single sticky message per channel.",
    "usage": "|stickies",
    "category": "utility",
    "exampleOutput": "✓ stickies  executed successfully.",
    "permission": "Administrator"
  },
  {
    "name": "suggestions setup",
    "description": "Launch the guided setup wizard (or provide a channel directly)",
    "usage": "|suggestions setup",
    "category": "social",
    "exampleOutput": "✓ suggestions setup executed successfully."
  },
  {
    "name": "suggestions config",
    "description": "Configure suggestion settings",
    "usage": "|suggestions config",
    "category": "social",
    "exampleOutput": "✓ suggestions config executed successfully."
  },
  {
    "name": "suggestions toggle",
    "description": "Enable or disable the suggestions module",
    "usage": "|suggestions toggle",
    "category": "social",
    "exampleOutput": "✓ suggestions toggle executed successfully."
  },
  {
    "name": "suggestions submit",
    "description": "Submit a suggestion",
    "usage": "|suggestions submit",
    "category": "social",
    "exampleOutput": "✓ suggestions submit executed successfully."
  },
  {
    "name": "suggestions approve",
    "description": "Approve a suggestion",
    "usage": "|suggestions approve",
    "category": "social",
    "exampleOutput": "✓ suggestions approve executed successfully."
  },
  {
    "name": "suggestions deny",
    "description": "Deny a suggestion",
    "usage": "|suggestions deny",
    "category": "social",
    "exampleOutput": "✓ suggestions deny executed successfully."
  },
  {
    "name": "suggestions implement",
    "description": "Mark a suggestion as implemented",
    "usage": "|suggestions implement",
    "category": "social",
    "exampleOutput": "✓ suggestions implement executed successfully."
  },
  {
    "name": "suggestions delete",
    "description": "Delete a suggestion entirely",
    "usage": "|suggestions delete",
    "category": "social",
    "exampleOutput": "✓ suggestions delete executed successfully."
  },
  {
    "name": "suggestions list",
    "description": "List suggestions",
    "usage": "|suggestions list",
    "category": "social",
    "exampleOutput": "✓ suggestions list executed successfully."
  },
  {
    "name": "suggestions my",
    "description": "View your own suggestions",
    "usage": "|suggestions my",
    "category": "social",
    "exampleOutput": "✓ suggestions my executed successfully."
  },
  {
    "name": "ticket",
    "description": "\udf9f️ Advanced support ticket configuration and management system",
    "usage": "|ticket",
    "category": "tickets",
    "exampleOutput": "🎫 Ticket system configured.",
    "permission": "Administrator"
  },
  {
    "name": "trivia",
    "description": "Spits out a random brain-teaser trivia question.",
    "usage": "|trivia",
    "category": "fun",
    "exampleOutput": "✓ trivia  executed successfully."
  },
  {
    "name": "unban",
    "description": "Unban a user from the server using their username",
    "usage": "|unban",
    "category": "moderation",
    "exampleOutput": "✅ User Unbanned\n**john_doe** has been successfully unbanned.",
    "permission": "BanMembers"
  },
  {
    "name": "unmute",
    "description": "Unmute a user",
    "usage": "|unmute",
    "category": "moderation",
    "exampleOutput": "✓ Removed timeout from @user",
    "permission": "ModerateMembers"
  },
  {
    "name": "unwarn",
    "description": "Remove a warning from a server member",
    "usage": "|unwarn",
    "category": "utility",
    "exampleOutput": "✓ unwarn  executed successfully.",
    "permission": "ModerateMembers"
  },
  {
    "name": "verification setup",
    "description": "Launch the interactive wizard configuration questionnaire drops",
    "usage": "|verification setup",
    "category": "verification",
    "exampleOutput": "✓ Verification system activated.",
    "permission": "Administrator"
  },
  {
    "name": "verification edit",
    "description": "✏️ Modify an existing verification configuration with a skippable wizard",
    "usage": "|verification edit",
    "category": "verification",
    "exampleOutput": "✓ Verification system activated.",
    "permission": "Administrator"
  },
  {
    "name": "verification delete",
    "description": "\uddd1️ Safely purge verification records with an absolute safety screen",
    "usage": "|verification delete",
    "category": "verification",
    "exampleOutput": "✓ Verification system activated.",
    "permission": "Administrator"
  },
  {
    "name": "verification disable",
    "description": "\udd34 Instantly shut down the lock validation gatekeeper layer",
    "usage": "|verification disable",
    "category": "verification",
    "exampleOutput": "✓ Verification system activated.",
    "permission": "Administrator"
  },
  {
    "name": "warn",
    "description": "Warn a server member",
    "usage": "|warn",
    "category": "moderation",
    "exampleOutput": "⚠ Official warning registered for @user (1st warning point)",
    "permission": "ModerateMembers"
  },
  {
    "name": "warnings",
    "description": "View warnings for a user",
    "usage": "|warnings",
    "category": "moderation",
    "exampleOutput": "Warnings profile for @user:\n- 1st Warn: Spam (Logged by @staff)\n- Total: 1",
    "permission": "ModerateMembers"
  },
  {
    "name": "welcome",
    "description": "Configure or toggle the welcome/leave system",
    "usage": "|welcome",
    "category": "setup",
    "exampleOutput": "✓ welcome  executed successfully.",
    "permission": "ManageGuild"
  },
  {
    "name": "wouldyourather",
    "description": "Presents an impossible split decision with interactive voting buttons.",
    "usage": "|wouldyourather",
    "category": "fun",
    "exampleOutput": "✓ wouldyourather  executed successfully."
  }
];

export const COMMAND_CATEGORIES = [
  "analytics",
  "automod",
  "fun",
  "leveling",
  "moderation",
  "roles",
  "setup",
  "social",
  "tickets",
  "utility",
  "verification",
  "voice"
];

export const COMMANDS_BY_CATEGORY = {
  "fun": [
    {
      "name": "8ball",
      "description": "\udfb1 Ask the magic 8-ball a question and receive a mystical fortune.",
      "usage": "|8ball",
      "category": "fun",
      "exampleOutput": "✓ 8ball  executed successfully."
    },
    {
      "name": "capital-quiz",
      "description": "Tests your geographic knowledge of world capitals.",
      "usage": "|capital-quiz",
      "category": "fun",
      "exampleOutput": "✓ capital-quiz  executed successfully."
    },
    {
      "name": "cat",
      "description": "Spits out a fully animated cat GIF and a random feline fact.",
      "usage": "|cat",
      "category": "fun",
      "exampleOutput": "✓ cat  executed successfully."
    },
    {
      "name": "coinflip",
      "description": "Flip an animated coin and see what it lands on.",
      "usage": "|coinflip",
      "category": "fun",
      "exampleOutput": "✓ coinflip  executed successfully."
    },
    {
      "name": "dadjoke",
      "description": "Get a classic, groans-guaranteed dad joke.",
      "usage": "|dadjoke",
      "category": "fun",
      "exampleOutput": "✓ dadjoke  executed successfully."
    },
    {
      "name": "dice-duel",
      "description": "Challenge another user to an instant dice rolling duel.",
      "usage": "|dice-duel",
      "category": "fun",
      "exampleOutput": "✓ dice-duel  executed successfully."
    },
    {
      "name": "dog",
      "description": "Spits out a cute puppy picture and a random canine fact.",
      "usage": "|dog",
      "category": "fun",
      "exampleOutput": "✓ dog  executed successfully."
    },
    {
      "name": "fortune",
      "description": "Reveals a prediction about your future.",
      "usage": "|fortune",
      "category": "fun",
      "exampleOutput": "✓ fortune  executed successfully."
    },
    {
      "name": "fun-menu",
      "description": "Explore what the Fun Module offers in a clean single-column directory.",
      "usage": "|fun-menu",
      "category": "fun",
      "exampleOutput": "✓ fun-menu  executed successfully."
    },
    {
      "name": "hug",
      "description": "Give a member a warm, fuzzy virtual hug.",
      "usage": "|hug",
      "category": "fun",
      "exampleOutput": "✓ hug  executed successfully."
    },
    {
      "name": "joke",
      "description": "Get a hilariously relatable, funny everyday joke.",
      "usage": "|joke",
      "category": "fun",
      "exampleOutput": "✓ joke  executed successfully."
    },
    {
      "name": "meme",
      "description": "Spits out a random funny, relatable lifestyle meme.",
      "usage": "|meme",
      "category": "fun",
      "exampleOutput": "✓ meme  executed successfully."
    },
    {
      "name": "predict-love",
      "description": "Calculate the ultimate romantic compatibility percentage.",
      "usage": "|predict-love",
      "category": "fun",
      "exampleOutput": "✓ predict-love  executed successfully."
    },
    {
      "name": "rate",
      "description": "Have the bot rate anything out of 10.",
      "usage": "|rate",
      "category": "fun",
      "exampleOutput": "✓ rate  executed successfully."
    },
    {
      "name": "roast",
      "description": "Deliver a savage, good-natured roast to a user.",
      "usage": "|roast",
      "category": "fun",
      "exampleOutput": "✓ roast  executed successfully."
    },
    {
      "name": "roll",
      "description": "Roll a random number or a multi-sided die.",
      "usage": "|roll",
      "category": "fun",
      "exampleOutput": "✓ roll  executed successfully."
    },
    {
      "name": "slap",
      "description": "Slap another user with a hilarious item.",
      "usage": "|slap",
      "category": "fun",
      "exampleOutput": "✓ slap  executed successfully."
    },
    {
      "name": "spacefact",
      "description": "Get a mind-blowing cosmic space fact.",
      "usage": "|spacefact",
      "category": "fun",
      "exampleOutput": "✓ spacefact  executed successfully."
    },
    {
      "name": "trivia",
      "description": "Spits out a random brain-teaser trivia question.",
      "usage": "|trivia",
      "category": "fun",
      "exampleOutput": "✓ trivia  executed successfully."
    },
    {
      "name": "wouldyourather",
      "description": "Presents an impossible split decision with interactive voting buttons.",
      "usage": "|wouldyourather",
      "category": "fun",
      "exampleOutput": "✓ wouldyourather  executed successfully."
    }
  ],
  "analytics": [
    {
      "name": "analytics setup",
      "description": "Deploy statistics channel grids (auto-refreshes every 1 min)",
      "usage": "|analytics setup",
      "category": "analytics",
      "exampleOutput": "📊 Analytics tracking deployed.",
      "permission": "Manage Server"
    },
    {
      "name": "analytics edit",
      "description": "✏️ Modify your existing statistics channel layout settings",
      "usage": "|analytics edit",
      "category": "analytics",
      "exampleOutput": "📊 Analytics tracking deployed.",
      "permission": "Manage Server"
    },
    {
      "name": "analytics delete",
      "description": "\uddd1️ Wipe current statistic channels and clear database traces",
      "usage": "|analytics delete",
      "category": "analytics",
      "exampleOutput": "📊 Analytics tracking deployed.",
      "permission": "Manage Server"
    },
    {
      "name": "analytics update",
      "description": "\udd04 Force an instant refresh (counters already auto-refresh every 1 min)",
      "usage": "|analytics update",
      "category": "analytics",
      "exampleOutput": "📊 Analytics tracking deployed.",
      "permission": "Manage Server"
    }
  ],
  "utility": [
    {
      "name": "autodelete",
      "description": "The auto-delete profile for ${channel} is now active.",
      "usage": "|autodelete",
      "category": "utility",
      "exampleOutput": "✓ autodelete  executed successfully.",
      "permission": "Administrator"
    },
    {
      "name": "automessage",
      "description": "Manage recurring scheduled message pings",
      "usage": "|automessage",
      "category": "utility",
      "exampleOutput": "✓ automessage  executed successfully.",
      "permission": "Administrator"
    },
    {
      "name": "capabilities",
      "description": "A full, detailed tour of everything the bot can do.",
      "usage": "|capabilities",
      "category": "utility",
      "exampleOutput": "✓ capabilities  executed successfully."
    },
    {
      "name": "channels",
      "description": "Create, edit, customize, and delete channels and categories.",
      "usage": "|channels",
      "category": "utility",
      "exampleOutput": "✓ channels  executed successfully.",
      "permission": "ManageChannels"
    },
    {
      "name": "embed create",
      "description": "Open a modal to build a new embed",
      "usage": "|embed create",
      "category": "utility",
      "exampleOutput": "✓ embed create executed successfully."
    },
    {
      "name": "embed edit",
      "description": "Load an existing bot embed into your session for editing",
      "usage": "|embed edit",
      "category": "utility",
      "exampleOutput": "✓ embed edit executed successfully."
    },
    {
      "name": "embed send",
      "description": "Send your in-progress embed to a channel",
      "usage": "|embed send",
      "category": "utility",
      "exampleOutput": "✓ embed send executed successfully."
    },
    {
      "name": "embed field add",
      "description": "Open a modal to add a field to your embed",
      "usage": "|embed field add",
      "category": "utility",
      "exampleOutput": "✓ embed add executed successfully."
    },
    {
      "name": "embed field remove",
      "description": "Remove a field from your embed by index",
      "usage": "|embed field remove",
      "category": "utility",
      "exampleOutput": "✓ embed remove executed successfully."
    },
    {
      "name": "embed field image",
      "description": "Set the large image URL on your embed",
      "usage": "|embed field image",
      "category": "utility",
      "exampleOutput": "✓ embed image executed successfully."
    },
    {
      "name": "embed thumbnail",
      "description": "Set the thumbnail URL on your embed",
      "usage": "|embed thumbnail",
      "category": "utility",
      "exampleOutput": "✓ embed thumbnail executed successfully."
    },
    {
      "name": "embed color",
      "description": "Set the embed color",
      "usage": "|embed color",
      "category": "utility",
      "exampleOutput": "✓ embed color executed successfully."
    },
    {
      "name": "embed footer",
      "description": "Set the embed footer",
      "usage": "|embed footer",
      "category": "utility",
      "exampleOutput": "✓ embed footer executed successfully."
    },
    {
      "name": "embed author",
      "description": "Set the embed author",
      "usage": "|embed author",
      "category": "utility",
      "exampleOutput": "✓ embed author executed successfully."
    },
    {
      "name": "embed preview",
      "description": "Preview your current in-progress embed",
      "usage": "|embed preview",
      "category": "utility",
      "exampleOutput": "✓ embed preview executed successfully."
    },
    {
      "name": "embed clear",
      "description": "Clear your in-progress embed session",
      "usage": "|embed clear",
      "category": "utility",
      "exampleOutput": "✓ embed clear executed successfully."
    },
    {
      "name": "embed template save",
      "description": "Save current embed as a named template",
      "usage": "|embed template save",
      "category": "utility",
      "exampleOutput": "✓ embed save executed successfully."
    },
    {
      "name": "embed template load",
      "description": "Load a saved template into your session",
      "usage": "|embed template load",
      "category": "utility",
      "exampleOutput": "✓ embed load executed successfully."
    },
    {
      "name": "embed list",
      "description": "List all saved templates for this server",
      "usage": "|embed list",
      "category": "utility",
      "exampleOutput": "✓ embed list executed successfully."
    },
    {
      "name": "embed delete",
      "description": "Delete a saved template",
      "usage": "|embed delete",
      "category": "utility",
      "exampleOutput": "✓ embed delete executed successfully."
    },
    {
      "name": "flavor",
      "description": "Discover your current ice cream flavor personality.",
      "usage": "|flavor",
      "category": "utility",
      "exampleOutput": "✓ flavor  executed successfully."
    },
    {
      "name": "guilds",
      "description": "Owner only: list all guilds the bot is in",
      "usage": "|guilds",
      "category": "utility",
      "exampleOutput": "✓ guilds  executed successfully.",
      "permission": "CreateInstantInvite"
    },
    {
      "name": "help",
      "description": "View the full list of available bot commands by category.",
      "usage": "|help",
      "category": "utility",
      "exampleOutput": "✓ help  executed successfully."
    },
    {
      "name": "invites",
      "description": "Advanced invite tracking system",
      "usage": "|invites",
      "category": "utility",
      "exampleOutput": "✓ invites  executed successfully.",
      "permission": "ManageGuild"
    },
    {
      "name": "mod-logs-toggle",
      "description": "Log all moderator actions into one channel.",
      "usage": "|mod-logs-toggle",
      "category": "utility",
      "exampleOutput": "✓ mod-logs-toggle  executed successfully.",
      "permission": "ManageGuild"
    },
    {
      "name": "mydata",
      "description": "No description",
      "usage": "|mydata",
      "category": "utility",
      "exampleOutput": "✓ mydata  executed successfully."
    },
    {
      "name": "premium",
      "description": "Premium includes everything in the Free tier, plus the additions below.",
      "usage": "|premium",
      "category": "utility",
      "exampleOutput": "✓ premium  executed successfully.",
      "permission": "SendMessages"
    },
    {
      "name": "purpose",
      "description": "Learn about the bot and see its profile picture",
      "usage": "|purpose",
      "category": "utility",
      "exampleOutput": "✓ purpose  executed successfully."
    },
    {
      "name": "rules",
      "description": "Generate and customize server rules.",
      "usage": "|rules",
      "category": "utility",
      "exampleOutput": "✓ rules  executed successfully.",
      "permission": "Administrator"
    },
    {
      "name": "starboard setup",
      "description": "Launch the setup wizard (or pass a channel to skip it)",
      "usage": "|starboard setup",
      "category": "utility",
      "exampleOutput": "✓ starboard setup executed successfully."
    },
    {
      "name": "starboard config",
      "description": "Configure a starboard setting",
      "usage": "|starboard config",
      "category": "utility",
      "exampleOutput": "✓ starboard config executed successfully."
    },
    {
      "name": "starboard ignore",
      "description": "Add a channel to the ignore list",
      "usage": "|starboard ignore",
      "category": "utility",
      "exampleOutput": "✓ starboard ignore executed successfully."
    },
    {
      "name": "starboard unignore",
      "description": "Remove a channel from the ignore list",
      "usage": "|starboard unignore",
      "category": "utility",
      "exampleOutput": "✓ starboard unignore executed successfully."
    },
    {
      "name": "starboard toggle",
      "description": "Enable or disable the starboard module",
      "usage": "|starboard toggle",
      "category": "utility",
      "exampleOutput": "✓ starboard toggle executed successfully."
    },
    {
      "name": "starboard force",
      "description": "Force-star a message by its ID",
      "usage": "|starboard force",
      "category": "utility",
      "exampleOutput": "✓ starboard force executed successfully."
    },
    {
      "name": "starboard stats",
      "description": "View starboard statistics for this server",
      "usage": "|starboard stats",
      "category": "utility",
      "exampleOutput": "✓ starboard stats executed successfully."
    },
    {
      "name": "stickies",
      "description": "Deploy and manage a single sticky message per channel.",
      "usage": "|stickies",
      "category": "utility",
      "exampleOutput": "✓ stickies  executed successfully.",
      "permission": "Administrator"
    },
    {
      "name": "unwarn",
      "description": "Remove a warning from a server member",
      "usage": "|unwarn",
      "category": "utility",
      "exampleOutput": "✓ unwarn  executed successfully.",
      "permission": "ModerateMembers"
    }
  ],
  "automod": [
    {
      "name": "automodrule setup",
      "description": "Launch the interactive configuration setup wizard node",
      "usage": "|automodrule setup",
      "category": "automod",
      "exampleOutput": "✓ automodrule setup executed successfully."
    },
    {
      "name": "automodrule edit",
      "description": "✏️ Modify your existing background filter parameter fields",
      "usage": "|automodrule edit",
      "category": "automod",
      "exampleOutput": "✓ automodrule edit executed successfully."
    },
    {
      "name": "automodrule delete",
      "description": "\uddd1️ Wipe current filter metrics cleanly out of memory rows",
      "usage": "|automodrule delete",
      "category": "automod",
      "exampleOutput": "✓ automodrule delete executed successfully."
    },
    {
      "name": "autoresponder",
      "description": "Configure each part below. Your changes preview live. Click **Save** when ready.",
      "usage": "|autoresponder",
      "category": "automod",
      "exampleOutput": "✓ autoresponder  executed successfully.",
      "permission": "ManageGuild"
    }
  ],
  "roles": [
    {
      "name": "autorole all",
      "description": "Apply role to everyone",
      "usage": "|autorole all",
      "category": "roles",
      "exampleOutput": "✓ Autorole configured successfully.",
      "permission": "Manage Roles"
    },
    {
      "name": "autorole humans",
      "description": "Apply role to humans only",
      "usage": "|autorole humans",
      "category": "roles",
      "exampleOutput": "✓ Autorole configured successfully.",
      "permission": "Manage Roles"
    },
    {
      "name": "autorole bots",
      "description": "Apply role to bots only",
      "usage": "|autorole bots",
      "category": "roles",
      "exampleOutput": "✓ Autorole configured successfully.",
      "permission": "Manage Roles"
    },
    {
      "name": "autorole ongoing",
      "description": "Inspect current active configurations",
      "usage": "|autorole ongoing",
      "category": "roles",
      "exampleOutput": "✓ Autorole configured successfully.",
      "permission": "Manage Roles"
    },
    {
      "name": "autorole delete",
      "description": "Purge all ongoing configs for everyone, bots, and humans",
      "usage": "|autorole delete",
      "category": "roles",
      "exampleOutput": "✓ Autorole configured successfully.",
      "permission": "Manage Roles"
    },
    {
      "name": "reactionroles create",
      "description": "Build and deploy a custom role assignment panel",
      "usage": "|reactionroles create",
      "category": "roles",
      "exampleOutput": "✅ Role panel deployed successfully.",
      "permission": "Manage Roles"
    },
    {
      "name": "reactionroles edit",
      "description": "✏️ Update the title or description text fields of an existing deployed panel",
      "usage": "|reactionroles edit",
      "category": "roles",
      "exampleOutput": "✅ Role panel deployed successfully.",
      "permission": "Manage Roles"
    },
    {
      "name": "reactionroles add-role",
      "description": "➕ Add a new assignment choice node directly into an existing active panel",
      "usage": "|reactionroles add-role",
      "category": "roles",
      "exampleOutput": "✅ Role panel deployed successfully.",
      "permission": "Manage Roles"
    },
    {
      "name": "reactionroles remove-role",
      "description": "➖ Remove a specific role assignment node out of an active panel framework",
      "usage": "|reactionroles remove-role",
      "category": "roles",
      "exampleOutput": "✅ Role panel deployed successfully.",
      "permission": "Manage Roles"
    },
    {
      "name": "reactionroles delete-panel",
      "description": "\uddd1️ Wipe a role panel entirely out of active channel registries and database nodes",
      "usage": "|reactionroles delete-panel",
      "category": "roles",
      "exampleOutput": "✅ Role panel deployed successfully.",
      "permission": "Manage Roles"
    },
    {
      "name": "reactionroles test",
      "description": "🧪 Diagnostic Simulator: Test component menus safely in a private sandbox view",
      "usage": "|reactionroles test",
      "category": "roles",
      "exampleOutput": "✅ Role panel deployed successfully.",
      "permission": "Manage Roles"
    },
    {
      "name": "role",
      "description": "Role management system",
      "usage": "|role",
      "category": "roles",
      "exampleOutput": "✓ Role management command executed successfully.",
      "permission": "ManageRoles"
    }
  ],
  "moderation": [
    {
      "name": "ban",
      "description": "Ban a user from the server",
      "usage": "|ban",
      "category": "moderation",
      "exampleOutput": "✓ Banned member @user (Reason: Malicious activity)",
      "permission": "BanMembers"
    },
    {
      "name": "kick",
      "description": "Kick a user from the server",
      "usage": "|kick",
      "category": "moderation",
      "exampleOutput": "✓ Kicked member @user",
      "permission": "KickMembers"
    },
    {
      "name": "lockdown",
      "description": "Freeze or thaw text channels during emergencies",
      "usage": "|lockdown",
      "category": "moderation",
      "exampleOutput": "✓ lockdown  executed successfully.",
      "permission": "Administrator"
    },
    {
      "name": "mute",
      "description": "Mute a user for a custom duration (1m to 28d)",
      "usage": "|mute",
      "category": "moderation",
      "exampleOutput": "✓ Timed out @user for 10m",
      "permission": "ModerateMembers"
    },
    {
      "name": "purge",
      "description": "Bulk delete messages using advanced filtering",
      "usage": "|purge",
      "category": "moderation",
      "exampleOutput": "✓ purge  executed successfully.",
      "permission": "Administrator"
    },
    {
      "name": "slowmode",
      "description": "Manage channel slowmode intervals",
      "usage": "|slowmode",
      "category": "moderation",
      "exampleOutput": "✓ slowmode  executed successfully.",
      "permission": "ManageMessages"
    },
    {
      "name": "unban",
      "description": "Unban a user from the server using their username",
      "usage": "|unban",
      "category": "moderation",
      "exampleOutput": "✅ User Unbanned\n**john_doe** has been successfully unbanned.",
      "permission": "BanMembers"
    },
    {
      "name": "unmute",
      "description": "Unmute a user",
      "usage": "|unmute",
      "category": "moderation",
      "exampleOutput": "✓ Removed timeout from @user",
      "permission": "ModerateMembers"
    },
    {
      "name": "warn",
      "description": "Warn a server member",
      "usage": "|warn",
      "category": "moderation",
      "exampleOutput": "⚠ Official warning registered for @user (1st warning point)",
      "permission": "ModerateMembers"
    },
    {
      "name": "warnings",
      "description": "View warnings for a user",
      "usage": "|warnings",
      "category": "moderation",
      "exampleOutput": "Warnings profile for @user:\n- 1st Warn: Spam (Logged by @staff)\n- Total: 1",
      "permission": "ModerateMembers"
    }
  ],
  "social": [
    {
      "name": "birthdays",
      "description": "Birthday management",
      "usage": "|birthdays",
      "category": "social",
      "exampleOutput": "✓ birthdays  executed successfully.",
      "permission": "ManageGuild"
    },
    {
      "name": "giveaway",
      "description": "Establish and manage customizable item drops",
      "usage": "|giveaway",
      "category": "social",
      "exampleOutput": "✓ giveaway  executed successfully.",
      "permission": "Administrator"
    },
    {
      "name": "poll",
      "description": "Create and manage polls",
      "usage": "|poll",
      "category": "social",
      "exampleOutput": "✓ poll  executed successfully.",
      "permission": "Administrator"
    },
    {
      "name": "suggestions setup",
      "description": "Launch the guided setup wizard (or provide a channel directly)",
      "usage": "|suggestions setup",
      "category": "social",
      "exampleOutput": "✓ suggestions setup executed successfully."
    },
    {
      "name": "suggestions config",
      "description": "Configure suggestion settings",
      "usage": "|suggestions config",
      "category": "social",
      "exampleOutput": "✓ suggestions config executed successfully."
    },
    {
      "name": "suggestions toggle",
      "description": "Enable or disable the suggestions module",
      "usage": "|suggestions toggle",
      "category": "social",
      "exampleOutput": "✓ suggestions toggle executed successfully."
    },
    {
      "name": "suggestions submit",
      "description": "Submit a suggestion",
      "usage": "|suggestions submit",
      "category": "social",
      "exampleOutput": "✓ suggestions submit executed successfully."
    },
    {
      "name": "suggestions approve",
      "description": "Approve a suggestion",
      "usage": "|suggestions approve",
      "category": "social",
      "exampleOutput": "✓ suggestions approve executed successfully."
    },
    {
      "name": "suggestions deny",
      "description": "Deny a suggestion",
      "usage": "|suggestions deny",
      "category": "social",
      "exampleOutput": "✓ suggestions deny executed successfully."
    },
    {
      "name": "suggestions implement",
      "description": "Mark a suggestion as implemented",
      "usage": "|suggestions implement",
      "category": "social",
      "exampleOutput": "✓ suggestions implement executed successfully."
    },
    {
      "name": "suggestions delete",
      "description": "Delete a suggestion entirely",
      "usage": "|suggestions delete",
      "category": "social",
      "exampleOutput": "✓ suggestions delete executed successfully."
    },
    {
      "name": "suggestions list",
      "description": "List suggestions",
      "usage": "|suggestions list",
      "category": "social",
      "exampleOutput": "✓ suggestions list executed successfully."
    },
    {
      "name": "suggestions my",
      "description": "View your own suggestions",
      "usage": "|suggestions my",
      "category": "social",
      "exampleOutput": "✓ suggestions my executed successfully."
    }
  ],
  "setup": [
    {
      "name": "cute",
      "description": "Configure cute text layouts for server setup templates",
      "usage": "|cute",
      "category": "setup",
      "exampleOutput": "✨ Cute Mode Configured! Layouts will now use Small Caps (sᴍᴀʟʟ ᴄᴀᴘs)!",
      "permission": "ManageGuild"
    },
    {
      "name": "fun-module",
      "description": "Enable or disable the fun commands module.",
      "usage": "|fun-module",
      "category": "setup",
      "exampleOutput": "✓ fun-module  executed successfully.",
      "permission": "ManageGuild"
    },
    {
      "name": "setup-audit",
      "description": "Configure, enable, or disable the server audit log channel.",
      "usage": "|setup-audit",
      "category": "setup",
      "exampleOutput": "✓ setup-audit  executed successfully.",
      "permission": "Administrator"
    },
    {
      "name": "setup",
      "description": "️ Provision specialized, high-density server configurations from blueprint templates.",
      "usage": "|setup",
      "category": "setup",
      "exampleOutput": "✓ Setup complete! Deployed: 📁 Welcome, 📁 Chats, 7 channels, and Admin/Mod/Member roles.",
      "permission": "ManageGuild"
    },
    {
      "name": "welcome",
      "description": "Configure or toggle the welcome/leave system",
      "usage": "|welcome",
      "category": "setup",
      "exampleOutput": "✓ welcome  executed successfully.",
      "permission": "ManageGuild"
    }
  ],
  "leveling": [
    {
      "name": "level leaderboard",
      "description": "Show the top 10 users by XP",
      "usage": "|level leaderboard",
      "category": "leveling",
      "exampleOutput": "📈 Leveling system updated."
    },
    {
      "name": "level settings",
      "description": "Configure leveling settings",
      "usage": "|level settings",
      "category": "leveling",
      "exampleOutput": "📈 Leveling system updated."
    },
    {
      "name": "level multiplier",
      "description": "Set a server-wide XP multiplier (e.g., 2 for Double XP)",
      "usage": "|level multiplier",
      "category": "leveling",
      "exampleOutput": "📈 Leveling system updated."
    },
    {
      "name": "level xp add",
      "description": "Add XP to a user",
      "usage": "|level xp add",
      "category": "leveling",
      "exampleOutput": "📈 Leveling system updated."
    },
    {
      "name": "level xp remove",
      "description": "Remove XP from a user",
      "usage": "|level xp remove",
      "category": "leveling",
      "exampleOutput": "📈 Leveling system updated."
    }
  ],
  "voice": [
    {
      "name": "selfvoice",
      "description": "\udf99️ Create self-managed temporary voice channels that clean themselves up.",
      "usage": "|selfvoice",
      "category": "voice",
      "exampleOutput": "🔊 Voice room created successfully.",
      "permission": "Administrator"
    }
  ],
  "tickets": [
    {
      "name": "ticket",
      "description": "\udf9f️ Advanced support ticket configuration and management system",
      "usage": "|ticket",
      "category": "tickets",
      "exampleOutput": "🎫 Ticket system configured.",
      "permission": "Administrator"
    }
  ],
  "verification": [
    {
      "name": "verification setup",
      "description": "Launch the interactive wizard configuration questionnaire drops",
      "usage": "|verification setup",
      "category": "verification",
      "exampleOutput": "✓ Verification system activated.",
      "permission": "Administrator"
    },
    {
      "name": "verification edit",
      "description": "✏️ Modify an existing verification configuration with a skippable wizard",
      "usage": "|verification edit",
      "category": "verification",
      "exampleOutput": "✓ Verification system activated.",
      "permission": "Administrator"
    },
    {
      "name": "verification delete",
      "description": "\uddd1️ Safely purge verification records with an absolute safety screen",
      "usage": "|verification delete",
      "category": "verification",
      "exampleOutput": "✓ Verification system activated.",
      "permission": "Administrator"
    },
    {
      "name": "verification disable",
      "description": "\udd34 Instantly shut down the lock validation gatekeeper layer",
      "usage": "|verification disable",
      "category": "verification",
      "exampleOutput": "✓ Verification system activated.",
      "permission": "Administrator"
    }
  ]
};
